spring:
  application:
    name: langchain4j-one

langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: sk-c814e0c394204926b26576ce5b580a12
        model-name: qwen-turbo-2025-04-28
      streaming-chat-model:
        api-key: sk-c814e0c394204926b26576ce5b580a12
        model-name: qwen-turbo-2025-04-28

